### ISSUE TITLE
Question: Is there a documentation how to install config and use?

### ISSUE THREAD

**Issue by bunhin** [acsone/click-odoo-contrib#100]
Hi @sbidoul ,
I installed with pip3.7 install click-odoo-contrib  in my Odoo 13 virtual enveironment (virtualenveironment is activated) than try the command   such as  click-odoo --help   or click-odoo-backupdb --help,   always  get error    ....ModuleNotFoundError: No module named 'openerp'  the error persist when i gave the odoo config file 

is there any guide how to install and config this package before i able to use it? or please just give a little guide for it
1. where do in need to install when my odoo using virtual environment? (now i installed it inside the virtual environment)
2. do i need to run the command inside odoo root folder?
3. in order to backup db and filestore  to a directory, do we need to set directory owner to odoo?

Please help, thank you

**Comment by sbidoul** [comment]
Perhaps Odoo is not installed in the virtualenv ? If you have not done something link `python -m pip install -e ./odoo` or another, similar installation command for Odoo, then this is it.

Also, try `python -c "import odoo; print(odoo.addons.__path__)"`, and try to see what is missing if that fails.

**Comment by bunhin** [comment]
Odoo is installed on /opt/odoo virtualenv in /home/odoo13,  i already in /opt/odoo13/ while the environment is activated  and this python -c "import odoo; print(odoo.addons.__path__)"   return  /opt/odoo13/odoo/addons

when i entered command   click-odoo-backupdb --help   return this error:

Traceback (most recent call last):
  File "/home/odoo13/odoo13/bin/click-odoo-backupdb", line 5, in <module>
    from click_odoo_contrib.backupdb import main
  File "/home/odoo13/odoo13/lib/python3.7/site-packages/click_odoo_contrib/backupdb.py", line 12, in <module>
    import click_odoo
  File "/home/odoo13/odoo13/lib/python3.7/site-packages/click_odoo/__init__.py", line 4, in <module>
    from .env import OdooEnvironment  # noqa
  File "/home/odoo13/odoo13/lib/python3.7/site-packages/click_odoo/env.py", line 17, in <module>
    import openerp as odoo
ModuleNotFoundError: No module named 'openerp'

**Comment by flotho** [comment]
Hi,

This one is well known.
Answer here https://github.com/acsone/click-odoo/issues/20#issuecomment-445483087
fully functional for me

**Comment by sbidoul** [comment]
The important is that click-odoo-contrib is installed in the same python environment than the one where Odoo is installed.
Or even more precisely, the python used to launch click-odoo must be one where `import odoo` works.

There are many ways to achieve that. Python is very flexible, and that's why it's sometime also complicated to understand
(although in the end, it's boils down to PYTHONPATH / sys.path).

So that is why I always recommend to create a virtualenv and work in it, i.e. install click-odoo-contrib in it, and also `pip install -e ./odoo` in it. Using `-e / --editable` will ensure that you don't have a second copy of Odoo.

**Comment by flotho** [comment]
> Hi, @flotho , Odoo instance was installed from source instead of Pip install Odoo, do i still need pip install -e /path_odoo? just worried for double installing

Hi @bunhin I had the exact same issue as yours.
Using the @sbidoul tip work perfect : 

> So that is why I always recommend to create a virtualenv and work in it, i.e. install click-odoo-contrib in it, and also `pip install -e ./odoo` in it. Using `-e / --editable` will ensure that you don't have a second copy of Odoo.

**Comment by bunhin** [comment]
thank you @sbidoul and @flotho ,  i already have as @sbidoul suggest. As i always install odoo on virtual env, also this click-odoo-contrib installed in the same environment (using same python in environment).  After i enter  Pip install -e /path_odoo it generate message every package required is satisfied  and finally say  "successfully install develop odoo"  and i found one new folder is created inside root odoo -->"odoo.egg-info" with bunch of files in it.  Then all click-odoo-contrib   command is now working. 

Only a bit wonder then with the the word 'develop'  inside the message "successfully install develop odoo"  worry if it refers to a development environment. The point to install this click-odoo-contrib is for backup and restore and other db operation in production instance not in development instance.   is it other alternative beside pip install -e /path_odoo    maybe with the export PATH=/..... :$PATH.  I am sorry if it is too long.

**Comment by sbidoul** [comment]
> Only a bit wonder then with the the word 'develop' inside the message "successfully install develop odoo" worry if it refers to a development environment.

@bunhin if you refer to the message you see in pip output when doing `pip install -e ./odoo`, then there is no reason to worry.
The `develop` word refers to `setup.py develop` which pip actually calls to do the editable install. But it is perfectly fit to run in production, no reason to worry about that.
