### ISSUE TITLE
click-odoo-update: Some actions are done after 'Modules loaded'

### ISSUE THREAD

**Issue by rousseldenis** [acsone/click-odoo-contrib#108]
I have an issue with click-odoo-update.

It seems that after 'Modules loaded' message, some actions are done that raise error. I have no error if I use 'odoo -u all' command.

I have these lines after 'Modules loaded':

![image](https://user-images.githubusercontent.com/19529533/138416209-48470cf9-190c-4200-bd8f-f6ad56c2e957.png)

And it seems that some post_init_hook actions are launched just after even if they have been done in update just before.

**Comment by sbidoul** [comment]
@rousseldenis shall we close this ?

**Comment by sbidoul** [comment]
This issue is not actionnable as is. Let's close it.
