### ISSUE TITLE
[Proposal] marabunta wrapper / port

### ISSUE THREAD

**Issue by blaggacao** [acsone/click-odoo-contrib#12]
[marabunta](https://github.com/camptocamp/marabunta) is a vanguard _descriptive_ migration controller, however it lacks the framework approach of the click ecosystem.
For the sake of standardization of Odoo scripting a odoo-click port would be a powerful citizen.

Note: Not everyone likes `auto_update (TM)` magic but rather prefers descriptive single sources of truth for (historic) migration paths.

If such port should be an option, I'd like to include an interface to the Odoo Enterprise upgrade API...

**Comment by sbidoul** [comment]
Marabunta is a standalone project that works well by itself. I don't see the need to integrate it here. Moreover it uses a anthem which as a scope similar to click-odoo.

**Comment by blaggacao** [comment]
If I were to predict the future: click-odoo beats anthem & marabunta beets auto_updates.
This suggestion is preempting this possible outcome. :wink:
