### ISSUE TITLE
click-odoo-backupdb: `subprocess` DeprecationWarning

### ISSUE THREAD

**Issue by psugne** [acsone/click-odoo-contrib#129]
Used:
python3.10
Odoo 16.0

Tested and noticed only on Odoo version 16.0

Traceback:
```
py.warnings: /opt/odoo/venv/lib/python3.10/site-packages/click_odoo_contrib/backupdb.py:28: DeprecationWarning: Since 16.0, just use `subprocess`.
  File "/opt/odoo/venv/bin/click-odoo-backupdb", line 8, in <module>
    sys.exit(main())
  File "/opt/odoo/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/odoo/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/odoo/venv/lib/python3.10/site-packages/click_odoo/env_options.py", line 199, in _invoke
    return self.org_invoke(ctx)
  File "/opt/odoo/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/odoo/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/odoo/venv/lib/python3.10/site-packages/click_odoo_contrib/backupdb.py", line 121, in main
    _dump_db(dbname, _backup)
  File "/opt/odoo/venv/lib/python3.10/site-packages/click_odoo_contrib/backupdb.py", line 28, in _dump_db
    _stdin, stdout = odoo.tools.exec_pg_command_pipe(*cmd)
```

A Warning comes on doing a backup from [here](https://github.com/acsone/click-odoo-contrib/blob/master/click_odoo_contrib/backupdb.py#L28) where Odoo warns about deprecation [here](https://github.com/odoo/odoo/blob/743e97667e44cdaab6db334d807cf3d409cea621/odoo/tools/misc.py#L77). Related with Odoo [commit](https://github.com/odoo/odoo/commit/7f14631fe804ffdcc82d8b2fc1d2e70e485bf806).

**Comment by JakubSs** [comment]
is there any update?

**Comment by psugne** [comment]
> is there any update?

Still no feedback

**Comment by sbidoul** [comment]
This still works in 17. No time to handle this today. A PR is welcome.

**Comment by peterromao** [comment]
I am having this too on Odoo 16.0 20240216 build.

Is this just a question of substituting
`_stdin, stdout = odoo.tools.exec_pg_command_pipe(*cmd)`
to
`_stdin, stdout = subprocess.run(cmd, env=env, stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT, check=True)`

?

I don't even know where to change this to test.

**Comment by schout-it** [comment]
odoo.tools.exec_pg_command_pipe is removed in v18, so this issue needs some eyes on it
so an import of subprocess and the substitution mentioned in the previous message should be enough

**Comment by sbidoul** [comment]
I'm setting the bug label, since it now breaks on 18.

A preliminary PR to run the test suite on 18 is at #150.

To be honest, we don't use these click-odoo-backup commands much at acsone anymore, so if anyone is willing to provide a PR this is most welcome.

**Comment by JakubSs** [comment]
@sbidoul there is already PR #152 to fix it, can it be approved asap, please? I am definitely not the only one waiting for it
