### ISSUE TITLE
[Proposal] Weblate integration

### ISSUE THREAD

**Issue by blaggacao** [acsone/click-odoo-contrib#13]
A standalone script to produce Weblate integration commits mainly run through CI, but also for ad-hoc local maintenance would be a great everyday's companion.

MQT tool related to this task are fine for travis et al, but does not have the superior UX of a standalone CLI tool. Transifex integration could be an option, too.

**Comment by sbidoul** [comment]
This is what click-odoo-makepot does.

**Comment by blaggacao** [comment]
Wow! Nice didn't realize... @sbidoul You definitely got a new contributor for this great lib...

**Comment by blaggacao** [comment]
That makes me happy!
