### ISSUE TITLE
 click-odoo-backupdb  Error: Destination already exist: /home/odoo/backup/

### ISSUE THREAD

**Issue by luismata01** [acsone/click-odoo-contrib#130]
Hi

When I try to create a backup this error is persistent, and I cannot bakup the database

![image](https://user-images.githubusercontent.com/43929688/229094352-a9aa5404-62bb-4ed0-85ff-fbb3732869b8.png)

I appreciate your contribution.

**Comment by sbidoul** [comment]
I think you must provide a file name, not a directory name as backup target.
