### ISSUE TITLE
click-odoo-restoredb: support neutralize option?

### ISSUE THREAD

**Issue by oerp-odoo** [acsone/click-odoo-contrib#135]
Now that odoo supports data neutralization (at least on v16 https://github.com/odoo/odoo/blob/ebc4ed6c4fb11b01be28cf417b27de83d5361cef/odoo/modules/neutralize.py#L25), I think it would be useful, to have this option via click odoo as well? 

And its convenient, because each module can implement their own neutralization scripts.

**Comment by sbidoul** [comment]
This makes sense, yes. Feel free to submit a PR.

**Comment by sbidoul** [comment]
On the other hand, what would it do differently than `odoo neutralize`?

**Comment by oerp-odoo** [comment]
> On the other hand, what would it do differently than `odoo neutralize`?

What I meant, was to be able to trigger odoo standard neutralization (when you run click-odoo restore), not implement some custom. Though it was only added on v16. For other versions, maybe we could have some solution? As odoo does not offer anything out of the box.

Either way, now its inconvenient to separately deal with data neutralization.

**Comment by yajo** [comment]
Fixed by #143. Would you mind publishing a new release?

**Comment by sbidoul** [comment]
Hm, 17.0 tests are broken, now...

**Comment by psugne** [comment]
> Hm, 17.0 tests are broken, now...

Hi @sbidoul any news here? Looks like fix was done quite a long time ago. Any chance to fix failing tests?

**Comment by sbidoul** [comment]
Waiting for https://github.com/odoo/odoo/pull/172154 to be backported to 17.0
