### ISSUE TITLE
[v15CE] click-odoo-backupdb [Errno 13] Permission denied:

### ISSUE THREAD

**Issue by luismata01** [acsone/click-odoo-contrib#138]
Hi
When I try to execute from my work directory outside the docker with this command:

`docker-compose run --rm odoo click-odoo-backupdb demo1 /root/odoo/15.0-teletrabajove/backup/bkdemo1-11-19-23_08-24.zip`

The Command fail with this error

![image](https://github.com/acsone/click-odoo-contrib/assets/43929688/3af58ab1-825e-45b3-8d27-b672b69b1181)

can you Help me please

**Comment by sbidoul** [comment]
This looks like a permission issue, possibly in the way you mount your docker volumes.
