### ISSUE TITLE
[Proposal] Better scaffolding implementation

### ISSUE THREAD

**Issue by blaggacao** [acsone/click-odoo-contrib#14]
Scaffolding implementation has several shortcomings, and chances are that Odoo is not going to develop it further: https://github.com/odoo/odoo/pull/26478#issuecomment-414592366

Shortcomings:
- https://github.com/odoo/odoo/pull/26480
- https://github.com/odoo/odoo/pull/26478
- https://github.com/xoe-labs/odoo-dev/tree/master-NOPR-add-cli-dialogue-to-scaffolding

Would it be worth the thought to implement a better scaffolding command on top of the `odoo-click` framework?

Link to myself: https://github.com/acsone/bobtemplates.odoo

**Comment by sbidoul** [comment]
For scaffolding you don't need an Odoo api.Environment. So this is out of scope for this project.

**Comment by blaggacao** [comment]
Good point, I was thinking of that. What makes the idea half'way attractive is the ecosystem-potential: `odoo-click` for all things Odoo CLI. But you're right, technically there is no interdependence.
