### ISSUE TITLE
click-odoo-initdb: "." in db names are valid...

### ISSUE THREAD

**Issue by blaggacao** [acsone/click-odoo-contrib#35]
... see this regex
https://github.com/acsone/click-odoo-contrib/blob/04c0715b96cbe3dd23ce33600b2d5e631314abf6/click_odoo_contrib/initdb.py#L28

**Comment by blaggacao** [comment]
[Well](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS), or rather [this introduces a odoo bug](https://github.com/odoo/odoo/commit/6d83f700144b29150050900430e8166d3d3345f7)?

**Comment by blaggacao** [comment]
Again from the [MySQL standard](https://dev.mysql.com/doc/refman/8.0/en/identifiers.html), `U+002E` (`.`) is allowed in quoted identifiers.

**Comment by blaggacao** [comment]
Conclusion after reading through it a little more: quoted identifies have almost no rules, so the database name must be quoted but otherwise not comply with a regex of any kind.

**Comment by sbidoul** [comment]
click-odoo-initdb has additional constraints in database naming for its caching mechanism to work.

Why is it a problem in practice to not allow dots in database names?

**Comment by blaggacao** [comment]
Currently, since v12, the odoo host matching mechanism has subtly changed. "." is no more a wildcard, so `odoo.com` would not match any more a database `odoo-com`

**Comment by blaggacao** [comment]
Is there any clash between Unicode Basic Multilingual Plane and the caching mechanism?

**Comment by sbidoul** [comment]
Done in #75
