### ISSUE TITLE
click-odoo-initdb: addons dir check is not done

### ISSUE THREAD

**Issue by blaggacao** [acsone/click-odoo-contrib#36]
It bothers me that: https://github.com/acsone/click-odoo-contrib/tree/master/tests/data/test_initdb/addon1
is not detected as an invalid addons directory, see [odoo code](https://github.com/odoo/odoo/blob/d7acfdae2b2d2feb320cb509b30b67082f80cfcd/odoo/tools/config.py#L511) (missing `__init__.py`)

**Comment by sbidoul** [comment]
Can you please provide the exact steps to reproduce the issue?

**Comment by sbidoul** [comment]
Can we close?

**Comment by blaggacao** [comment]
Yeah, if it doesn't bother you. I'm still playing around with my fork, so for now I don't depend on this... :wink:
