### ISSUE TITLE
Error: Access denied

### ISSUE THREAD

**Issue by rwngallego** [acsone/click-odoo-contrib#42]
I get an error here: https://github.com/acsone/click-odoo-contrib/blob/04c0715b96cbe3dd23ce33600b2d5e631314abf6/click_odoo_contrib/backupdb.py#L30

Error: Access denied

No logs are shown so I have no further details. Is there any special requirement in the Postgresql privileges?

**Comment by sbidoul** [comment]
@rwngallego there should be a stack trace. Without it there is not much we can do to diagnose your issue.

**Comment by rwngallego** [comment]
I've figured out. It's related to this issue: https://github.com/acsone/click-odoo-contrib/issues/40 Once I've enabled the list_db setting, it worked.
