### ISSUE TITLE
click-odoo-initdb question

### ISSUE THREAD

**Issue by gridworkz** [acsone/click-odoo-contrib#53]
Hello: I've created a few template dbs in Odoo and I would like to get an example of using click-odoo-initdb to create a new database from one of these templates. If you have a working example syntax of it that would be great. I'm just a little confused on how to create/access the cache of template dbs.

**Comment by sbidoul** [comment]
`click-odoo-initdb` manages it's cache automatically. If you call it several time with the same list of modules in `--modules` you'll see it goes faster and reuses cached templates.

If you want to clone a database you have created yourself, you can use `click-odoo-copydb`.

**Comment by sbidoul** [comment]
You might also be interested in #24 and #25 which are open for contribution (or funding).

**Comment by gridworkz** [comment]
Ah OK, thanks so much. Dumb question - So that list of modules isn't the whole Odoo base addons list but you're own custom addons?

**Comment by sbidoul** [comment]
It can be any module that is in addons-path.

**Comment by gridworkz** [comment]
Thnx - looks like copydb is what I'm looking for

**Comment by gridworkz** [comment]
One last Python noob question - how do I install click-odoo-contrib? I've got click-odoo installed. I assume you run everything from the Odoo instance itself.

**Comment by sbidoul** [comment]
setup.py indeed expects the default encoding is utf-8. We could fix that, but a question first: do you really need to install from source? `python -m pip install click-odoo-contrib` should just work fine.

**Comment by sbidoul** [comment]
Closing as no answer.
