### ISSUE TITLE
Merge back dodoo-* enhancements?

### ISSUE THREAD

**Issue by blaggacao** [acsone/click-odoo-contrib#60]
This is a question to check opinions about merging back dodoo-* enhancements into click-odoo-*. At the time of forking I needed lifecycle control, especially over click-odoo.

I haven't checked, but that's maybe not a hindrance any more.

I'd like to contribute mainly those

- dodoo-migrator (descriptive migration option inspired by marabunta with integration to Odoo upgrade service)
- dodoo-loader with helps in ETL taska
- dodoo-snapshotter (which does - kind of - incremental backups for the filestore part)
- improvements to initialized and copbydb to allow raw SQL.

Is there a chance I can sunset my fork and incorporate those things here?

**Comment by sbidoul** [comment]
> migrator, loader, snapshotter

These look quite too big and complex for this project. Of course the scope of click-odoo-contrib project is not well delimitated, but I'd rather like to limit it to small, simple tools with excellent test coverage.

I'd encourage you to create standalone project for these, and as I said before we'll be happy to maintain a list of projects using `click-odoo` to provide visibility.

> improvements to initialized and copbydb to allow raw SQL.

These might be interesting. Can you provide more explanations and/or specific pointers about what it is about (in a separate feature-request like issue preferably).

**Comment by blaggacao** [comment]
Ok.
> These might be interesting. Can you provide more explanations and/or specific pointers about what it is about (in a separate feature-request like issue preferably).


Actually I dropped the raw SQL support in favor of small python scripts which use the ORM as the preferred way of "seeding" databases.

I don't think anymore this has been a good idea. Plaulin click-odoo scripts cover the use case (better).
