### ISSUE TITLE
click-odoo-update: add option to filter modules to be updated

### ISSUE THREAD

**Issue by gustavovalverde** [acsone/click-odoo-contrib#66]
A common scenario, mostly in multi-tenant environments, is to update a specific set of modules (or a single one) instead of all the modules that has been changed since the last update. Sometimes you don't even want to upgrade everything.

It could be a parameter like `--modules` / `-m`

**Comment by rousseldenis** [comment]
@gustavovalverde if you use click-odoo-update once, second pass will update only changed modules. See README for more information

**Comment by rousseldenis** [comment]
@gustavovalverde Usually, that command has to be called 'per environment'. Could you explain a little more the use case you have?

**Comment by gustavovalverde** [comment]
@rousseldenis for example, I have a kubernetes cluster, each version <11, 12, 13> has their own containers. I commonly use a script like this one https://github.com/acsone/click-odoo-contrib/issues/39#issuecomment-594094440 to upgrade all the databases from a single version, but sometimes I don't want (nor can wait) a full upgrade.

**Comment by rousseldenis** [comment]
Usually, if a set of modules has changed, it is safe to update them, no?

As the update process should be agnostic (and generic).

If you want to bypass this, why not using the classic -u?

**Comment by gustavovalverde** [comment]
`If you want to bypass this, why not using the classic -u?`

Actually, that's what I'm doing:
for db in <db_list>; do odoo --stop-after-init --no-http --log-level=warn -u <modules> -d $db; done

This would be just a way to keep the same script for both behaviors.

**Comment by sbidoul** [comment]
@gustavovalverde would #69 help for your use case?

**Comment by gustavovalverde** [comment]
Yes, that would work, in a common scenario it makes more sense to actually "filter-out" problematic modules, instead of doing the inverse.

Closing this in favor of that approach.
