### ISSUE TITLE
Question regarding logging

### ISSUE THREAD

**Issue by flotho** [acsone/click-odoo-contrib#99]
Hi,

I would like to know where are stored the logs?
I set up logfile option in the conf file but nothing is log inside.

Thanks for your feedback

**Comment by sbidoul** [comment]
click-odoo does not do anything special with logging. It's just regular Odoo logging. Please provide details about what you are trying to do and what is not working as you expect.

**Comment by flotho** [comment]
hummm... my bad 
It seems that only the log level is not used because in the end, I have this in my log file : 
![image](https://user-images.githubusercontent.com/1043935/129029864-c30e7f6a-eeab-4943-afc7-a42de5d9bd1a.png)

**Comment by sbidoul** [comment]
Yes click-odoo-initdb set the logging level to WARN unless you set it with `--log-level`. Perhaps it should honor what the config file says if there is one and `--log-level` is not used ? Food for thought ...

**Comment by flotho** [comment]
thanks for the info
